
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://postgres:5432/db_user
    username: db_user
    password: db_user
  liquibase:
    url: jdbc:postgresql://postgres:5432/db_user
    user: db_user-liquibase
    password: db_user-liquibase

web:
  client:
    study:
      storage:
        url: http://study-storage-service:8081/api/storage

logging:
  level:
    hse.cs.se.user.service: trace